% Indizes für die Variablen für Kriterien der Nullraumbewegung.
% Dient zur Vermeidung hart kodierter Indizes im Quelltext
% 
% Eingabe:
% Type
%   Typ des Roboters. 0/1=SerRob, 2=ParRob
% 
% Ausgabe:
% idx_ikpos_wn
%   Gewichtungsfaktoren in der Einzelpunkt-IK (Eingabe-Variable `wn`)
% idx_ikpos_hn
%   Zielfunktionen in der Einzelpunkt-IK (Ausgabe-Variable `h`)
%   Index 1 in der Funktion ist die Summe. 1 hier ist also dort 2.
% idx_iktraj_wnP
%   Gewichtungsfaktoren der P-Verstärkungen in der Trajektorien-IK
%   bezogen auf die Beschleunigung (in der Eingabe-Variable `wn`)
% idx_iktraj_wnD
%   Gewichtungsfaktoren der D-Verstärkungen in der Trajektorien-IK
%   bezogen auf die Beschleunigung. Ist also eine P-Verstärkung auf die 
%   Geschwindigkeit (auch in der Eingabe-Variable `wn`)
% idx_iktraj_hn
%   Zielfunktionen in der Trajektorien-IK
% 
% Siehe auch: SerRob/invkin2, SerRob/invkin2_traj, ParRob/invkin3, 
%             ParRob/invkin4, ParRob/invkin_traj, ParRob/invkin2_traj
% (dort sind die Indizes im IK-Algorithmus verwendet)

% Moritz Schappler, moritz.schappler@imes.uni-hannover.de, 2021-12
% (C) Institut für Mechatronische Systeme, Leibniz Universität Hannover

function [idx_ikpos_wn, idx_ikpos_hn, idx_iktraj_wnP, idx_iktraj_wnD, ...
  idx_iktraj_hn] = ik_optimcrit_index(Type)

if Type < 2 % SerRob
  idx_ikpos_wn = struct( ...
    'length', 8, ... % Anzahl der Elemente in indiziertem Vektor
    'qlim_par', 1, ...
    'qlim_hyp', 2, ...
    'jac_cond', 3, ...
    'coll_hyp', 4, ...
    'instspc_hyp', 5, ...
    'xlim_par', 6, ...
    'xlim_hyp', 7, ...
    'coll_par', 8);
  % Gleiche Reihenfolge in Ausgabe-Variable h
  idx_ikpos_hn = idx_ikpos_wn;
  % Trajektorien-Indizes, aufgeteilt in P- und D-Anteil
  idx_iktraj_wnP = struct( ...
    'length', 19, ... % Anzahl der Elemente in indiziertem Vektor
    'qlim_par', 1, ...
    'qlim_hyp', 2, ...
    'qDlim_par', 3, ...
    'qDlim_hyp', 4, ...
    'jac_cond', 5, ...
    'coll_hyp', 9, ...
    'instspc_hyp', 11, ...
    'xlim_par', 13, ...
    'xlim_hyp', 15, ...
    'xDlim_par', 17, ...
    'coll_par', 18);
  idx_iktraj_wnD = struct( ...
    'length', 19, ... % Anzahl der Elemente in indiziertem Vektor
    'qlim_par', 6, ...
    'qlim_hyp', 7, ...
    'jac_cond', 8, ...
    'coll_hyp', 10, ...
    'instspc_hyp', 12, ...
    'xlim_par', 14, ...
    'xlim_hyp', 16, ...
    'coll_par', 19);
  idx_iktraj_hn = struct( ...
    'length', 11, ... % Anzahl der Elemente in indiziertem Vektor
    'qlim_par', 1, ...
    'qlim_hyp', 2, ...
    'qDlim_par', 3, ...
    'qDlim_hyp', 4, ...
    'jac_cond', 5, ...
    'coll_hyp', 6, ...
    'instspc_hyp', 7, ...
    'xlim_par', 8, ...
    'xlim_hyp', 9, ...
    'xDlim_par', 10, ...
    'coll_par', 11);
else % ParRob
  idx_ikpos_wn = struct( ...
    'length', 9, ... % Anzahl der Elemente in indiziertem Vektor
    'qlim_par', 1, ...
    'qlim_hyp', 2, ...
    'ikjac_cond', 3, ...
    'jac_cond', 4, ...
    'coll_hyp', 5, ...
    'instspc_hyp', 6, ...
    'xlim_par', 7, ...
    'xlim_hyp', 8, ...
    'coll_par', 9);
  % Gleiche Reihenfolge in Ausgabe-Variable h
  idx_ikpos_hn = idx_ikpos_wn;
  % Trajektorien-Indizes, aufgeteilt in P- und D-Anteil
  idx_iktraj_wnP = struct( ...
    'length', 21, ... % Anzahl der Elemente in indiziertem Vektor
    'qlim_par', 1, ...
    'qlim_hyp', 2, ...
    'qDlim_par', 3, ...
    'qDlim_hyp', 4, ...
    'ikjac_cond', 5, ...
    'jac_cond', 6, ...
    'coll_hyp', 11, ...
    'instspc_hyp', 13, ...
    'xlim_par', 15, ...
    'xlim_hyp', 17, ...
    'xDlim_par', 19, ...
    'coll_par', 20);
  idx_iktraj_wnD = struct( ...
    'length', 21, ... % Anzahl der Elemente in indiziertem Vektor
    'qlim_par', 7, ...
    'qlim_hyp', 8, ...
    'ikjac_cond', 9, ...
    'jac_cond', 10, ...
    'coll_hyp', 12, ...
    'instspc_hyp', 14, ...
    'xlim_par', 16, ...
    'xlim_hyp', 18, ...
    'coll_par', 21);
  idx_iktraj_hn = struct( ...
    'length', 12, ... % Anzahl der Elemente in indiziertem Vektor
    'qlim_par', 1, ...
    'qlim_hyp', 2, ...
    'qDlim_par', 3, ...
    'qDlim_hyp', 4, ...
    'ikjac_cond', 5, ...
    'jac_cond', 6, ...
    'coll_hyp', 7, ...
    'instspc_hyp', 8, ...
    'xlim_par', 9, ...
    'xlim_hyp', 10, ...
    'xDlim_par', 11, ...
    'coll_par', 12);
end

