% Kompiliere alle Funktionen, die als Mex-Datei aufgerufen werden
% Betrifft Aufrufe aus der Matlab-Klasse heraus

% Moritz Schappler, schappler@imes.uni-hannover.de, 2022-11
% (C) Institut für Mechatronische Systeme, Leibniz Universität Hannover


matlabfcn2mex({ ...
  'rigidbody_gravloadB_floatb_eulxyz_slag_vp2', ...
  'rigidbody_gravloadB_floatb_eulxyz_reg2_slag_vp', ...
  'rigidbody_coriolisvecB_floatb_eulxyz_slag_vp2', ...
  'rigidbody_coriolisvecB_floatb_eulxyz_reg2_slag_vp', ...
  'rigidbody_inertiaB_floatb_eulxyz_slag_vp2', ...
  'rigidbody_inertiaB_floatb_eulxyz_reg2_slag_vp', ...
  'rigidbody_invdynB_floatb_eulxyz_slag_vp2', ...
  'rigidbody_invdynB_floatb_eulxyz_reg2_slag_vp'});
matlabfcn2mex({'check_collisionset_simplegeom'});
matlabfcn2mex({'euljac', 'euljacD', 'adjoint_jacobian', 'adjointD_jacobian'});
